### ISSUE TITLE
PlatformException fired when longitude is negative in locationFromAddress method on iOS

### ISSUE THREAD

**Issue by Rahuvich** [Baseflow/flutter-geocoding#12]
## 🐛 Bug Report
[Only on iOS]
When trying to pass an address which longitude is negative (for example "81 Allée Joseph Pascal
31500 Pau") `locationFromAddress` method fires `PlatformException`.

```
[VERBOSE-2:ui_dart_state.cc(166)] Unhandled Exception: PlatformException(IO_ERROR, Error Domain=kCLErrorDomain Code=8 "(null)", null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:572:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:161:18)
<asynchronous suspension>
#2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:334:12)
#3      MethodChannelGeocoding.locationFromAddress (package:geocoding_platform_interface/src/implementations/method_channel_geocoding.dart:28:44)
#4      locationFromAddress (package:geocoding/geocoding.dart:22:32)
#5      _MapAddressState._updateAddress (package:jumpets_app/ui/components/maps/google_map_shelters.dart:49:32)
#6      _MapAddressState.didUpdateWidget (package:jumpets_app/ui/components/maps/google_map_shelters.dart:28:7)
#7      StatefulElement.update (package:flutter/src/widgets/framework.dart:4734:58)
#8      Element.updateChild (package:flut<…>
```

### Expected behavior

The expected behavior is the resulted Location of `address`

### Configuration

**Version:** 
  geocoding: ^1.0.3+1
```

$ flutter doctor -v
[✓] Flutter (Channel stable, 1.20.1, on Mac OS X 10.15.6 19G2021, locale
    es-ES)
    • Flutter version 1.20.1 at /Users/raulmateobeneyto/flutter
    • Framework revision 2ae34518b8 (6 weeks ago), 2020-08-05 19:53:19
      -0700
    • Engine revision c8e3b94853
    • Dart version 2.9.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version
    29.0.2)
    • Android SDK at /Users/raulmateobeneyto/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at:
      /Library/Java/JavaVirtualMachines/jdk1.8.0_192.jdk/Contents/Home/bin
      /java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_192-b12)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4, Build version 11E146
    • CocoaPods version 1.8.4

[!] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit
      https://flutter.dev/docs/get-started/install/macos#android-setup for
      detailed instructions).

[✓] VS Code (version 1.49.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

[✓] Connected device (1 available)
    • iPhone 11 Pro (mobile) • D2CC28C5-236E-449A-A0F3-5B96652F3D58 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-13-4 (simulator)

! Doctor found issues in 1 category.
```

**Platform:** 
- [X] :iphone: iOS
- [ ] :robot: Android

**Comment by mvanbeusekom** [comment]
@Rahuvich thank you for submitting this issue. I have looked into it and found that in this case Apple cannot find a result for the given address (according to Apple's definition "kCLErrorDomain Code=8" means "[kCLErrorGeocodeFoundNoResult](https://developer.apple.com/documentation/corelocation/clerror/kclerrorgeocodefoundnoresult)".

Of course this should not be something that causes a crash on the geocoding plugin and I will be working on that to make sure the geocoding plug-in will return a `null` (as is also the case on Android, if the Android implementation cannot do the translation).

**Comment by Rahuvich** [comment]
@mvanbeusekom Thank you, that would be awesome. 👍

**Comment by Bobby9292** [comment]
Just experienced that on Android like @mvanbeusekom mentioned.
I moved my code to a try-catch block and create a dummy Placemark in the the catch block with "unknown address" to handle this.

**Comment by mvanbeusekom** [comment]
@Rahuvich we have just release version 1.0.4 of the geocoding plug-in. 

After some internal discussions we decided not to return `null` but a custom exception explaining clearly the address was not found. So in your case you can use the code like this:

```dart
List<Location> locations = null;

try {
    locations = await locationFromAddress("81 Allée Joseph Pascal 31500 Pau");
} on NoResultFoundException {
    // Handle "No results found for the address"
    ...
}
```

Will be closing this issue now, but please leave a message if you have any questions.
