### ISSUE TITLE
Android: PlatformException(error, d != java.lang.Double, null)

### ISSUE THREAD

**Issue by matthewlloyd** [Baseflow/flutter-geocoding#5]
## 🐛 Bug Report

The following exception occurs on Android if the underlying platform fails to find address information:

```
E/MethodChannel#flutter.baseflow.com/geocoding(18312): Failed to handle method call
E/MethodChannel#flutter.baseflow.com/geocoding(18312): java.util.IllegalFormatConversionException: d != java.lang.Double
E/MethodChannel#flutter.baseflow.com/geocoding(18312): 	at java.util.Formatter$FormatSpecifier.failConversion(Formatter.java:4403)
E/MethodChannel#flutter.baseflow.com/geocoding(18312): 	at java.util.Formatter$FormatSpecifier.printInteger(Formatter.java:2885)
E/MethodChannel#flutter.baseflow.com/geocoding(18312): 	at java.util.Formatter$FormatSpecifier.print(Formatter.java:2839)
E/MethodChannel#flutter.baseflow.com/geocoding(18312): 	at java.util.Formatter.format(Formatter.java:2524)
E/MethodChannel#flutter.baseflow.com/geocoding(18312): 	at java.util.Formatter.format(Formatter.java:2459)
E/MethodChannel#flutter.baseflow.com/geocoding(18312): 	at java.lang.String.format(String.java:2870)
E/MethodChannel#flutter.baseflow.com/geocoding(18312): 	at com.baseflow.geocoding.MethodCallHandlerImpl.onPlacemarkFromCoordinates(MethodCallHandlerImpl.java:137)
E/MethodChannel#flutter.baseflow.com/geocoding(18312): 	at com.baseflow.geocoding.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:40)
E/MethodChannel#flutter.baseflow.com/geocoding(18312): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:230)
E/MethodChannel#flutter.baseflow.com/geocoding(18312): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#flutter.baseflow.com/geocoding(18312): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
E/MethodChannel#flutter.baseflow.com/geocoding(18312): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#flutter.baseflow.com/geocoding(18312): 	at android.os.MessageQueue.next(MessageQueue.java:335)
E/MethodChannel#flutter.baseflow.com/geocoding(18312): 	at android.os.Looper.loop(Looper.java:183)
E/MethodChannel#flutter.baseflow.com/geocoding(18312): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/MethodChannel#flutter.baseflow.com/geocoding(18312): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter.baseflow.com/geocoding(18312): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/MethodChannel#flutter.baseflow.com/geocoding(18312): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

The format specifiers do not match the argument types at lines https://github.com/Baseflow/flutter-geocoding/blob/master/geocoding/android/src/main/java/com/baseflow/geocoding/MethodCallHandlerImpl.java#L128 https://github.com/Baseflow/flutter-geocoding/blob/master/geocoding/android/src/main/java/com/baseflow/geocoding/MethodCallHandlerImpl.java#L137.

### Configuration

**Version:** 1.0.1

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android

**Comment by mvanbeusekom** [comment]
@matthewlloyd thank you for pointing this out. I have just released version 1.0.2 which should fix this problem.
